from django.db import models
from cabot.cabotapp.alert import AlertPlugin, AlertPluginUserData

from os import environ as env

from django.conf import settings
from django.core.urlresolvers import reverse
from django.template import Context, Template

import requests

msteams_template = "Service {{ service.name }} {% if service.overall_status == service.PASSING_STATUS %}is back to normal{% else %}reporting {{ service.overall_status }} status{% endif %}: {{ scheme }}://{{ host }}{% url 'service' pk=service.id %}. {% if service.overall_status != service.PASSING_STATUS %}Checks failing: {% for check in service.all_failing_checks %}{% if check.check_category == 'Jenkins check' %}{% if check.last_result.error %} {{ check.name }} ({{ check.last_result.error|safe }}) {{jenkins_api}}job/{{ check.name }}/{{ check.last_result.job_number }}/console{% else %} {{ check.name }} {{jenkins_api}}/job/{{ check.name }}/{{check.last_result.job_number}}/console {% endif %}{% else %} {{ check.name }} {% if check.last_result.error %} ({{ check.last_result.error|safe }}){% endif %}{% endif %}{% endfor %}{% endif %}{% if alert %}{% for alias in users %} @{{ alias }}{% endfor %}{% endif %}"

# This provides the hipchat alias for each user. Each object corresponds to a User
class MSTeamsAlert(AlertPlugin):
    name = "MSTeams"
    author = "mk"

    def send_alert(self, service, users, duty_officers):
        alert = True
        users = list(users) + list(duty_officers)

        if service.overall_status == service.WARNING_STATUS:
            alert = False  # Don't alert at all for WARNING
        if service.overall_status == service.ERROR_STATUS:
            if service.old_overall_status in (service.ERROR_STATUS, service.ERROR_STATUS):
                alert = False  # Don't alert repeatedly for ERROR
        if service.overall_status == service.PASSING_STATUS:
            color = 'green'
            if service.old_overall_status == service.WARNING_STATUS:
                alert = False  # Don't alert for recovery from WARNING status
        else:
            color = 'red'

        c = Context({
            'service': service,
            'users': users,
            'host': settings.WWW_HTTP_HOST,
            'scheme': settings.WWW_SCHEME,
            'alert': alert,
            'jenkins_api': settings.JENKINS_API,
        })
        message = Template(msteams_template).render(c)
        self._send_msteams_alert(message, color=color, service=service.name, sender='Cabot/%s' % service.name)

    def _send_msteams_alert(self, message, color='green', service, sender='Cabot'):

        channel = env.get('MSTEAMS_ALERT_CHANNEL')
        url = env.get('MSTEAMS_ALERT__URL')

        resp = requests.post(url, data={
	    "@type" : "MessageCard",
	    "@context" : "http://schema.org/extensions",
	    "summary" : service + " status",
	    "themeColor" : "ff0000",
	    "title" : service + " alert",
	     "sections" : [
		{
			"activityTitle": "**Alert generated by Cabot.**",
			"activitySubtitle": "at " + tstamp + "UCT",
			"facts" [
			{
				"message" : message
			}
			]
		"text" : "Description of Cabot alert."
		]
# Here, we can add 'potentialAction' section with links to cabot, jenkins, etc
		}

        })
